### ISSUE TITLE
Generated HTML are in single line

### ISSUE THREAD

**Issue by HKervadec** [MIDL-Conference/midl-website-builder#1]
This makes some debug/checks harder (as I need to first run a prettyfier). 

This could be done directly at the [end of the builder](https://github.com/MIDL-Conference/midl-website-builder/blob/master/mwb/builder.py#L290), with BeautifulSoup:
```python

from bs4 import BeautifulSoup

[...]

                    # Clean up HTML
                    html = html.replace('\r\n', '\n').replace('\r', '\n')
                    html = self.html_minifier.minify(html)
                    soup = BeautifulSoup(html, 'html.parser')  # Soup is made here
                    html = soup.prettify()  # and then the rest doesn't have to change

                    # Write HTML to output directory
                    filename = permalink[1:]
                    if filename == '' or filename.endswith('/'):
                        filename += 'index.html'

                    html_file = path.join(dstdir, filename)
                    if self.verbose and path.exists(html_file):
                        print('   warning: overwriting existing page with same name!')

                    html_dir = path.dirname(html_file)
                    makedirs(html_dir, exist_ok=True)
                    with open(html_file, 'w', encoding='utf-8') as file_stream:
                        file_stream.write(html)
```

But perhaps there is a reason not to do that ?

**Comment by nlessmann** [comment]
The HTML is minified to end up with smaller files, which also removes the line breaks. Seems a bit silly to first minify and then prettify. Maybe better use the developer tools of your browser for debugging? Or this could be added as an optional step that can be enabled when building locally. Maybe that would be helpful?

**Comment by HKervadec** [comment]
> The HTML is minified to end up with smaller files, which also removes the line breaks

The way I undestood it, the minifier also removes the commented content (which is good). 

> Or this could be added as an optional step that can be enabled when building locally. Maybe that would be helpful?

Yes, it would be helpful ; this way one hasn't to get out of its text editor. Do you want me to do a pull request for the feature ?

**Comment by nlessmann** [comment]
Yes, that would be great.

**Comment by HKervadec** [comment]
Implemented in https://github.com/MIDL-Conference/midl-website-builder/pull/2 .

Not fully sure we need a version bump for this.
